---
title: "Traffic Report"
---

Page 1
=====================================  

Row
-------------------------------------

### Last Update: `r Sys.Date()`

```{r version_value_box}
# valueBox to display the date of the latest update
# title indicating the month that is considered
last_observed_month <- df$date %>% max() %>% lubridate::month(label  = TRUE,
                                                             abbr   = FALSE,
                                                             locale = "en_US.UTF-8")
lastUpdateValue <- paste(last_observed_month,
                         df$date %>% max() %>% lubridate::year(),
                         sep = " ")

valueBox(value = lastUpdateValue,
         color = grey,
         icon = "glyphicon-calendar")
```

Row
-------------------------------------
    
Column {data-width=600}
-------------------------------------
    
### Chart 1
    
```{r}
```
   
Column {data-width=400}
-------------------------------------
   
### Chart 2

```{r}
```   
 
### Chart 3
    
```{r}
```

Page 2 {data-orientation=rows}
=====================================     
   
Row {data-height=600}
-------------------------------------

### Chart 1

```{r}
```

Row {data-height=400}
-------------------------------------
   
### Chart 2

```{r overallVisits, echo = FALSE}
valueBoxes(df, "Lights", "visits")
```  
    
### Chart 3

```{r}
```
